"""modify users table

Revision ID: 153aaec9bc18
Revises: e3833610bfb7
Create Date: 2025-06-04 20:23:35.641287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153aaec9bc18'
down_revision: Union[str, None] = 'e3833610bfb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verified_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verified_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
