"""create login_tokens table

Revision ID: 6af5df128356
Revises: 7abda117a216
Create Date: 2025-06-13 16:10:58.640010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6af5df128356'
down_revision: Union[str, None] = '7abda117a216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_tokens', sa.Column('token', sa.String(), nullable=False))
    op.add_column('login_tokens', sa.Column('expires', sa.DateTime(), nullable=False))
    op.alter_column('login_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('login_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_column('login_tokens', 'refresh_token')
    op.drop_column('login_tokens', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('login_tokens', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('login_tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('login_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('login_tokens', 'expires')
    op.drop_column('login_tokens', 'token')
    # ### end Alembic commands ###
