"""update login_tokens table

Revision ID: 8ae84e04fcd8
Revises: 6af5df128356
Create Date: 2025-06-13 16:13:41.915402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ae84e04fcd8'
down_revision: Union[str, None] = '6af5df128356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_tokens', sa.Column('refresh_token', sa.String(), nullable=False))
    op.add_column('login_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('login_tokens', 'token')
    op.drop_column('login_tokens', 'expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_tokens', sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('login_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('login_tokens', 'expires_at')
    op.drop_column('login_tokens', 'refresh_token')
    # ### end Alembic commands ###
