"""delete column category

Revision ID: b35f429a1317
Revises: 27c9932cadb6
Create Date: 2025-06-17 00:11:20.230540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35f429a1317'
down_revision: Union[str, None] = '27c9932cadb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
