"""update projects table

Revision ID: fba33f8a751d
Revises: b35f429a1317
Create Date: 2025-06-18 14:43:40.418514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba33f8a751d'
down_revision: Union[str, None] = 'b35f429a1317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('iban_details', sa.String(), nullable=False))
    op.drop_constraint('projects_category_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'category_id')
    op.drop_column('projects', 'owner')
    op.drop_column('projects', 'url_donations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('url_donations', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('projects_category_id_fkey', 'projects', 'categories', ['category_id'], ['id'])
    op.drop_column('projects', 'iban_details')
    # ### end Alembic commands ###
